version: 2

sources:
  - name: snowflake_sample
    description: 'sample database in snowflake'
    database: snowflake_sample_data
    schema: TPCDS_SF10TCL
    tables:
      - name: store_sales
        description: 'details about sales in store'